
trigger:
- main

variables:
  tag_id: $(Build.BuildId)

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - job: Build
        displayName: Build Job
        pool:
          vmImage: ubuntu-latest
        steps:
          - bash: echo "this works"
          - task: Docker@2
            inputs:
              containerRegistry: 'acr-abin-final'
              repository: 'starter/abinapp'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: $(tag_id)
          
