
trigger:
- main

variables:
  tag_id: $(Build.BuildId)

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - job: Build
        displayName: Build Job
        pool:
          vmImage: ubuntu-latest
        steps:
          - bash: echo "this works"
          - task: Docker@2
            inputs:
              containerRegistry: 'acr-abin-final'
              repository: 'starter/abinapp'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: $(tag_id)
          
          - bash: echo "the contents of the source directory are:"; ls -lRt $(System.DefaultWorkingDirectory)
          - bash: echo "the contents of the target directory are:"; ls -lRt $(Build.ArtifactStagingDirectory)
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)/kube-manifests'
              Contents: '**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
          
          - bash: echo "the contents of the target directory after copy are"; ls -lRt $(Build.ArtifactStagingDirectory)
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'kube-manifests'
              publishLocation: 'Container'

