apiVersion : apps/v1
kind: Deployment
metadata:
  name: newapp1 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newapp1
  template:
    metadata:
      labels:
        app: newapp1 
    spec:
      containers:
        - name: newapp1 
          image: abinacr.azurecr.io/newapp1
          ports:
          - containerPort: 80